<a href="https://colab.research.google.com/github/nagao-cs/DataAnalysis-learning/blob/main/Numpy_Learnnig.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
print(a.shape)
print(a.ndim)
print(a.size)

(3,)
1
3


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(b.shape)
print(b.ndim)
print(b.size)

(3, 3)
2
9


In [6]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
c = np.full((3, 3), 9)
print(c)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [9]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
e = np.random.random((5, 4))
print(e)

[[0.89664887 0.16044694 0.84373377 0.95239289]
 [0.94683848 0.01415772 0.83589474 0.00167453]
 [0.94271811 0.97385545 0.45590529 0.81458265]
 [0.24506854 0.85306969 0.01725881 0.71261504]
 [0.28018397 0.42052146 0.30116071 0.51332051]]


In [11]:
f = np.arange(3, 10, 2)
print(f)

[3 5 7 9]


In [12]:
val = e[2, 1]
print(val)

0.9738554455423998


In [13]:
center = d[1:3, 1:4]
print(center)
print(center.shape)

[[1. 0. 0.]
 [0. 1. 0.]]
(2, 3)


In [14]:
e[1:len(e), 1:len(e[0]-2)] = 0
print(e)
print(len(e))
print(len(e[0]))

[[0.89664887 0.16044694 0.84373377 0.95239289]
 [0.94683848 0.         0.         0.        ]
 [0.94271811 0.         0.         0.        ]
 [0.24506854 0.         0.         0.        ]
 [0.28018397 0.         0.         0.        ]]
5
4


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(np.array([a[0,1], a[2,1], a[1,0]]))
print(a[[0, 2, 1], [1, 1, 0]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 8 4]
[2 8 4]


In [16]:
x = np.arange(3)
x.dtype

dtype('int64')

In [17]:
y = np.arange(3.0)
print(y)
y.dtype

[0. 1. 2.]


dtype('float64')

In [18]:
x = np.arange(1, 5, 1, dtype=np.float32)
print(x)
x.dtype

x = x.astype(np.int64)
print(x, x.dtype)

[1. 2. 3. 4.]
[1 2 3 4] int64


In [19]:
a = np.arange(1,10).reshape(3, 3)
b = np.arange(1, 10).reshape(3, 3)
c = a + b
print(c)
c = a - b
print(c)
c = a * b
print(c)
c = a / b
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
c = np.sqrt(b)
print(c)
c = np.power(b, 2)
print(c == b**2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [21]:
b = np.arange(1, 4)
c = a + b
print(c)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [22]:
a = np.arange(1, 4)
print(a)
b = np.full((3), 2)
print(b)
c = a * b
print(c)
print(a * 2)

[1 2 3]
[2 2 2]
[2 4 6]
[2 4 6]


In [23]:
a = np.random.randint(0, 10, (2, 1, 3))
b = np.random.randint(0, 10, (3, 1))
print(a, a.shape)
print(b, b.shape)

c = a + b
print(c, c.shape)


[[[4 3 5]]

 [[3 4 3]]] (2, 1, 3)
[[9]
 [1]
 [1]] (3, 1)
[[[13 12 14]
  [ 5  4  6]
  [ 5  4  6]]

 [[12 13 12]
  [ 4  5  4]
  [ 4  5  4]]] (2, 3, 3)


In [24]:
print("Original b:", b.shape)
b_expand = b[np.newaxis, :, :]
print("Expanded b:", b_expand.shape)
b_expand_2 = b[:, np.newaxis, :]
print("Expanded b:", b_expand_2.shape)

Original b: (3, 1)
Expanded b: (1, 3, 1)
Expanded b: (3, 1, 1)


In [25]:
a = np.random.randint(0, 10, (5, 5))
b = np.arange(1, 6)
print(a, b)
c = np.empty((5, 5))

[[2 1 5 4 1]
 [7 6 3 4 8]
 [0 8 8 6 2]
 [5 9 3 9 4]
 [1 2 9 5 3]] [1 2 3 4 5]


In [ ]:
%%timeit
for i in range(a.shape[0]):
  c[i, :] = a[i, :] + b

In [ ]:
print(c)

In [ ]:
%%timeit
c = a + b

In [ ]:
a = np.arange(9).reshape(3, 3)
b  =np.arange(1, 10).reshape(3, 3)
c = np.dot(a, b)
print(c)
c = a.dot(b)
print(c)
c = a @ b
print(c)

In [ ]:
x = np.random.randint(0, 10, (8, 10))
print(x)

In [ ]:
print(x.mean())
print(x.var())
print(x.std())
print(x.max())
print(x.min())

In [ ]:
print(x.mean(axis=1))